version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - echo "Building the application..."
  post_build:
    commands:
      - echo "Build completed!"
artifacts:
  files:
    - '**/*'
  discard-paths: no
